# SPDX-License-Identifier: MPL-2.0

name: Publish documentation to gh-pages

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Doxygen Documentation
        uses: mattnotmitt/doxygen-action@v1.9
        with:
          working-directory: docs
      - name: Upload HTML output as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/doxygen/html
  
  deploy:
    if: github.ref == 'refs/heads/develop' && github.repository_owner == 'alpaka-group'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
